"""vocabulary review tracks grammar settings sharing

Revision ID: 04bea7bb47a2
Revises: 79d2d50326fd
Create Date: 2026-07-27 20:55:53.534233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04bea7bb47a2'
down_revision: Union[str, Sequence[str], None] = '79d2d50326fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('word_normalized', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('forms_drill_enabled', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_normalized', name='uq_cards_user_word')
    )
    op.create_index(op.f('ix_cards_user_id'), 'cards', ['user_id'], unique=False)
    op.create_index(op.f('ix_cards_word_normalized'), 'cards', ['word_normalized'], unique=False)
    op.create_table('note_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_note_categories_user_name')
    )
    op.create_index(op.f('ix_note_categories_user_id'), 'note_categories', ['user_id'], unique=False)
    op.create_table('study_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('new_goal', sa.Integer(), nullable=False),
    sa.Column('review_goal', sa.Integer(), nullable=False),
    sa.Column('is_goal_met', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_study_days_user_day')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme', sa.Enum('LIGHT', 'DARK', 'SYSTEM', name='themeenum'), nullable=False),
    sa.Column('study_direction', sa.Enum('EN_UK', 'UK_EN', 'MIXED', name='studydirectionenum'), nullable=False),
    sa.Column('tts_enabled', sa.Boolean(), nullable=False),
    sa.Column('tts_autoplay', sa.Boolean(), nullable=False),
    sa.Column('tts_accent', sa.Enum('AUTO', 'US', 'GB', name='ttsaccentenum'), nullable=False),
    sa.Column('tts_slow', sa.Boolean(), nullable=False),
    sa.Column('daily_new_goal', sa.Integer(), nullable=False),
    sa.Column('daily_review_goal', sa.Integer(), nullable=False),
    sa.Column('fsrs_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fsrs_parameters_version', sa.SmallInteger(), nullable=True),
    sa.Column('desired_retention', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_id', name='uq_user_settings_user')
    )
    op.create_table('word_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('imported_from_user_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imported_from_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_word_lists_user_name')
    )
    op.create_index(op.f('ix_word_lists_user_id'), 'word_lists', ['user_id'], unique=False)
    op.create_table('card_list_links',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['word_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'list_id')
    )
    op.create_table('grammar_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['note_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_notes_category_id'), 'grammar_notes', ['category_id'], unique=False)
    op.create_index(op.f('ix_grammar_notes_user_id'), 'grammar_notes', ['user_id'], unique=False)
    op.create_table('list_shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['word_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_list_shares_list_id'), 'list_shares', ['list_id'], unique=False)
    op.create_index(op.f('ix_list_shares_owner_id'), 'list_shares', ['owner_id'], unique=False)
    op.create_table('review_tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.Enum('TRANSLATION', 'FORMS', name='reviewkindenum'), nullable=False),
    sa.Column('state', sa.Enum('NEW', 'LEARNING', 'REVIEW', 'RELEARNING', name='reviewstateenum'), nullable=False),
    sa.Column('step', sa.SmallInteger(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'kind', name='uq_review_tracks_card_kind')
    )
    op.create_index('ix_review_tracks_due_at', 'review_tracks', ['due_at'], unique=False)
    op.create_table('word_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('transcription', sa.String(length=100), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_forms_card_id'), 'word_forms', ['card_id'], unique=False)
    op.create_table('word_senses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('part_of_speech', sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'ADVERB', 'PREPOSITION', 'PHRASE', 'OTHER', name='partofspeechenum'), nullable=True),
    sa.Column('translation', sa.String(length=255), nullable=True),
    sa.Column('gloss', sa.String(length=255), nullable=True),
    sa.Column('transcription', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('USER', 'AI', 'IMPORT', name='contentsourceenum'), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_senses_card_id'), 'word_senses', ['card_id'], unique=False)
    op.create_table('review_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('review_duration', sa.Integer(), nullable=True),
    sa.Column('state_before', sa.Enum('NEW', 'LEARNING', 'REVIEW', 'RELEARNING', name='reviewstateenum'), nullable=False),
    sa.Column('due_at_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 4', name='ck_review_logs_rating_range'),
    sa.ForeignKeyConstraint(['track_id'], ['review_tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_logs_track_id'), 'review_logs', ['track_id'], unique=False)
    op.create_index('ix_review_logs_user_reviewed_at', 'review_logs', ['user_id', 'reviewed_at'], unique=False)
    op.create_table('sense_examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('text_uk', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('USER', 'AI', 'IMPORT', name='contentsourceenum'), nullable=False),
    sa.Column('sense_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sense_id'], ['word_senses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sense_examples_sense_id'), 'sense_examples', ['sense_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sense_examples_sense_id'), table_name='sense_examples')
    op.drop_table('sense_examples')
    op.drop_index('ix_review_logs_user_reviewed_at', table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_track_id'), table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index(op.f('ix_word_senses_card_id'), table_name='word_senses')
    op.drop_table('word_senses')
    op.drop_index(op.f('ix_word_forms_card_id'), table_name='word_forms')
    op.drop_table('word_forms')
    op.drop_index('ix_review_tracks_due_at', table_name='review_tracks')
    op.drop_table('review_tracks')
    op.drop_index(op.f('ix_list_shares_owner_id'), table_name='list_shares')
    op.drop_index(op.f('ix_list_shares_list_id'), table_name='list_shares')
    op.drop_table('list_shares')
    op.drop_index(op.f('ix_grammar_notes_user_id'), table_name='grammar_notes')
    op.drop_index(op.f('ix_grammar_notes_category_id'), table_name='grammar_notes')
    op.drop_table('grammar_notes')
    op.drop_table('card_list_links')
    op.drop_index(op.f('ix_word_lists_user_id'), table_name='word_lists')
    op.drop_table('word_lists')
    op.drop_table('user_settings')
    op.drop_table('study_days')
    op.drop_index(op.f('ix_note_categories_user_id'), table_name='note_categories')
    op.drop_table('note_categories')
    op.drop_index(op.f('ix_cards_word_normalized'), table_name='cards')
    op.drop_index(op.f('ix_cards_user_id'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###

    # Alembic не прибирає типи ENUM за drop_table — без цього повторний
    # upgrade падає на "type ... already exists".
    for enum_name in (
        'contentsourceenum',
        'partofspeechenum',
        'reviewkindenum',
        'reviewstateenum',
        'studydirectionenum',
        'themeenum',
        'ttsaccentenum',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
